# Generated by Django 5.2.1 on 2025-05-28 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cultura',
            new_name='Culturas',
        ),
        migrations.RenameModel(
            old_name='HistoricalCultura',
            new_name='HistoricalCulturas',
        ),
        migrations.RenameModel(
            old_name='HistoricalSafra',
            new_name='HistoricalSafras',
        ),
        migrations.RenameModel(
            old_name='Safra',
            new_name='Safras',
        ),
    ]
