# Generated by Django 5.2.1 on 2025-05-26 02:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('codigo_ibge', models.IntegerField(help_text='Código numérico único do estado fornecido pelo IBGE.', unique=True, verbose_name='Código IBGE do Estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla do Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('codigo_ibge', models.IntegerField(db_index=True, help_text='Código numérico único da cidade fornecido pelo IBGE.', verbose_name='Código IBGE da Cidade')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localidades.estado', verbose_name='Estado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cidade',
                'verbose_name_plural': 'historical Cidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('codigo_ibge', models.IntegerField(db_index=True, help_text='Código numérico único do estado fornecido pelo IBGE.', verbose_name='Código IBGE do Estado')),
                ('sigla', models.CharField(db_index=True, max_length=2, verbose_name='Sigla do Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Estado',
                'verbose_name_plural': 'historical Estados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('codigo_ibge', models.IntegerField(help_text='Código numérico único da cidade fornecido pelo IBGE.', unique=True, verbose_name='Código IBGE da Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='localidades.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['estado__nome', 'nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
    ]
