# Generated by Django 5.2.1 on 2025-05-26 23:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cidade',
            new_name='Cidades',
        ),
        migrations.RenameModel(
            old_name='Estado',
            new_name='Estados',
        ),
        migrations.RenameModel(
            old_name='HistoricalCidade',
            new_name='HistoricalCidades',
        ),
        migrations.RenameModel(
            old_name='HistoricalEstado',
            new_name='HistoricalEstados',
        ),
    ]
