# Generated by Django 5.2.1 on 2025-05-25 18:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProdutor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, help_text='O usuário do sistema associado a este perfil de produtor.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.usuarios', verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'historical Produtor Rural',
                'verbose_name_plural': 'historical Produtores Rurais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado.', verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação do registro.', verbose_name='Data de Modificação')),
                ('nome', models.CharField(help_text='Nome do registro.', max_length=255, verbose_name='Nome')),
                ('usuario', models.OneToOneField(help_text='O usuário do sistema associado a este perfil de produtor.', on_delete=django.db.models.deletion.CASCADE, related_name='produtor_perfil', to='usuarios.usuarios', verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Produtor Rural',
                'verbose_name_plural': 'Produtores Rurais',
            },
        ),
    ]
