# Generated by Django 5.2.1 on 2025-05-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0002_rename_historicalprodutor_historicalprodutores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprodutores',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='nome',
        ),
    ]
