# Generated by Django 5.2.1 on 2025-05-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_historicalusuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
    ]
